on:
  release:
    types: [created]

jobs:
  release:
    name: ${{ matrix.os }}-release
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    strategy:
      matrix:
        os: ['windows', 'linux', 'darwin']

    steps:
    - uses: actions/checkout@v3
    - uses: wangyoucao577/go-release-action@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: ${{ matrix.os }}
        goarch: amd64
