name: test
on: pull_request

jobs:
  all:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v2
      with:
        go-version: '1.20.2'
    - run: go test
